(* Problem 12
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 * 
 *                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *     28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
*)

(* Solution *)

program p12;

const divisors = 500;

function count_factors(n : longint) : longint;
var
   i : longint;
begin
   count_factors := 0;
   for i := 1 to round(sqrt(n)) do
      if (n mod i = 0) then
         if (n / i = i) then
            count_factors := count_factors + 1
         else
            count_factors := count_factors + 2;
end;

var
   i        : longint = 1; 
   count    : longint = 0;
   triangle : longint = 0;
begin
   repeat
      triangle := triangle + i;
      i        := i + 1;
      count    := count_factors(triangle);
   until not (count < divisors);
   
   writeln('Answer is: ', triangle);
end.
