(* Problem 02
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
*)

(* Solution *)

program p2;

const n = 4000000;
   
var
   f1  : longint = 1;
   f2  : longint = 2;
   sum : longint = 0;
begin
   while f2 < n do
      begin
         if f1 mod 2 = 0 then sum += f1;
         if f2 mod 2 = 0 then sum += f2;
         
         f1 += f2; f2 += f1;
      end;
   writeln('Answer is: ', sum);
end.
